import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/header/Navbar";
import ModalWrapper from "@/components/ui/Modal/ModalWrapper";
import ShoppingCard from "@/components/ui/Modal/ShoppingCard";
import Catalog from "@/components/ui/Modal/Catalog";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar />
        <ModalWrapper title="Кошик" search="shopCard">
          <ShoppingCard />
        </ModalWrapper>
        <ModalWrapper title="Каталог товарів" search="catalog">
          <Catalog />
        </ModalWrapper>
        <main>{children}</main>
      </body>
    </html>
  );
}
